### ISSUE TITLE
Do a better job of publishing all our semi-permanent, rarely changing, documents in one place

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#111]
Just noticing with #2, #51 #57, #103, and #93 that it might be beneficial to have a better handle on the publically available organizing docs that don't change often.

Our current set up:
- all current versions of public docs available by year (e.g, 2017, 2018, 2019)
- staging area Google Drive for editable private-ish things (mostly when drafting, some for full conf planning
- "view-only" nextcloud https://share.mayfirst.org for all organizers, password-protected with financial docs, invoices, contact info and PII from past years (only 2018, 2019) <-- each co-organizer could be given an individual acct with this

We should discuss, and I think this is a post-event task, but I'm wondering if we'd do better by:
- [x] moving slow moving public docs into a policies/protocols/tactics repo
- keeping annual repos to just planning for that year 
- rejiging nextcloud as our working area with each organizer having accts
- [x] better moving over our private archive to nextcloud (move 2018, 2019 archive from google drive to nextcloud)
- tapering off google drive where possible and replace with nextcloud

**Comment by benhylau** [comment]
First attempt https://github.com/ournetworks/orga/pull/1

**Comment by dcwalk** [comment]
We've largely agreed to do this and implemented the orga repo and move to nextcloud. Acct creation will be covered in #2
