### ISSUE TITLE
Select video conferencing application for remote presentation + Q&A

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2019#118]
From: https://github.com/ournetworks/2019/issues/33#issuecomment-523540989

We have the following remote presentations:

| Day | Session | Presenter(s) |
|:----|:--------|:-------------|
| 1 | Whose future are you serving?: Interrogating frontier imaginaries within P2P technologies |  Laniyuk |
| 1 | Cryptoeconomics: Towards mass behavioral engineering or a network commons? | Jaya Klara Brekke, Dan Hassan |
| 2 | Solar powered website | Marie Otsuka, Lauren Traugott-Campbell |
| 2 | Amazonification: Decoding scarcity as weaponized precarity | Hiba Ali | 

There are gaps in between so we can set up the call with each presenter ahead of time.

---

- [x] Call app
- [x] Q&A process

**Comment by benhylau** [comment]
Evaluated a couple tools, here are some notes, in order of preference:
- **Zoom** has the best UI and call quality, Free allows for unlimited 1:1 calls but only 40 min for group calls, we should get Pro for a month (CAD 20) if any of the talks have more than 2 remote presenters
- **Hangouts** it works
- **Wire** has good quality screen share but cannot have presenter video while screen sharing, and cannot do group video calls unless it's a Pro plan, which still only supports max 4 participants with video (open source and e2e encrypted which is nice)
- **Jitsi** server not always reliable, and some clients have audio issues
- **BigBlueButton** screen share is sometime flaky :( nice that clients don't need to install an app

Plan to use Zoom and then Hangouts as backup.

**Comment by benhylau** [comment]
For Q&A we should use [sli.do](https://www.sli.do/) again as we did last year!

**Comment by dcwalk** [comment]
Can we avoid using sli.do?  What about.setting up a matrix room in
advance.folks can join, accepting questions from twitter / SSB?

It just feels like sli.do is another tool and one designed for like an
aesthetic / vibe of participation that is a little distant

**Comment by benhylau** [comment]
Matrix room makes sense, we did use matrix for last year too for the hack days. Maybe we can get ppl on it even before the conference as a general coordinating tool. In this case we should indicate in the email that goes out ahead of conference / on website.

**Comment by yisiliu** [comment]
> Hangouts it works
ROFL

I haven't tried Wire's Pro version so that was a problem when I was recommending that to you. It also shows a very good security standard, as in https://www.securemessagingapps.com/

**Comment by dcwalk** [comment]
This issue is a little confusing to me in relation to #80, does this superscede that? Are all the other prep bits for remote being handled? 

It kind of seems like we could have one place to review from?

**Comment by benhylau** [comment]
@dcwalk seems they are crossing. Merging this back to #80 and re-scope this title to figuring out the app.
