### ISSUE TITLE
Lanyard/Printed Program

### ISSUE THREAD

**Issue by garrying** [ournetworks/2019#120]
Copy: https://hackmd.io/jhorq6X4TKOOLswdxe-ZBg

**Comment by garrying** [comment]
The "Spirit" section needs work

Side 1 (Panel folds 1-3:
![Untitled-1](https://user-images.githubusercontent.com/227587/64933984-d15da980-d815-11e9-8569-fee42d637409.png)

Side 2 (Panel fold 4, Program):
![Untitled-12](https://user-images.githubusercontent.com/227587/64933996-e63a3d00-d815-11e9-8ed5-847539451b06.png)

**Comment by dcwalk** [comment]
We made and printed these!
