### ISSUE TITLE
Review CFP submission process

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#24]
Do we want to use the same CFP submission process as last year? I know we are also including unprogrammed // open spaces so we should revisit regardless

**Comment by benhylau** [comment]
I think the general templated GitHub Issues + email option worked well last year. Low overhead for us and no one complained.

The lightning talk process could use some improvement, perhaps just have a paper sign up sheet at the venue is sufficient.

Re: "unprogrammed // open spaces", perhaps CCC style, apply for a guaranteed area (GitHub Issues again) but can be set up ad-hoc in open areas?

**Comment by dcwalk** [comment]
We discussed! tweaks to the repo were made: https://github.com/ournetworks/2019-submissions
