### ISSUE TITLE
Apply for grants funding

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#28]
Just adding an issue to track a thing that has already been going on:

- [x] Apply for TAC grant
- [x] Apply for OAC grant
- [ ] Apply for that last one ??

**Comment by dcwalk** [comment]
@ana0 was there another grant on the horizon? Or two and done? :tada: :100: (already huge!)

**Comment by ana0** [comment]
There is one more!  It doesn't have a formal deadline, but I've been meaning to look into the timelines. Probably still needs to be submitted some minimum amount before the event.  Will email soon

**Comment by dcwalk** [comment]
Okay thanks for update! Much more able to help this round :)

**Comment by dcwalk** [comment]
At the call today we realized we are not eligible for the last grant. that means we've apppppllllliiiiieeeedddddd :mega: . closing
