### ISSUE TITLE
Use probot "settings" app to configure 2019 repo

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#4]
Picking up on a previous recommendation from @patcon, would people be up for using Settings, to have a `.github/settings.yml` file to quickly repeat repo configs? I'm thinking about this and setting up the 2019 and meetings repo at the same time

Details: https://github.com/probot/settings
The note at the bottom ("Note that this app inherently escalates anyone with push permissions to the admin role, since they can push config settings to the master branch, which will be synced") does not appear to be a show stopper given the tight nature of github org members.

Could we have a quick gut check on this issue and confirm at our first meeting on Tuesday, Jan 15?

**Comment by patcon** [comment]
I fully support this proposal!

**Comment by dcwalk** [comment]
This was merged! It works! :dancer:... closing
