### ISSUE TITLE
Update organizers info

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#41]
With @thinkbulecount2 onboard we need to update some places:

- [x] this [README](https://github.com/ournetworks/2019/blob/master/README.md)
- [x] the [ournetworks.ca/about (for now!)](https://ournetworks.ca/about/) see the code: [about.md](https://github.com/ournetworks/ournetworks.ca/blob/master/about.md)
   - [x] @thinkbulecount2 --> https://github.com/ournetworks/ournetworks.ca/pull/102
   - [x] @garrying --> https://github.com/ournetworks/ournetworks.ca/pull/111
  - [x] @dcwalk  --> https://github.com/ournetworks/ournetworks.ca/pull/110
  - [x] @benhylau  --> https://github.com/ournetworks/ournetworks.ca/pull/110 
  - [x] @ana0  --> https://github.com/ournetworks/ournetworks.ca/pull/107

**Comment by dcwalk** [comment]
Hey @thinkbulecount2 are you able to share a bio, preferred name, + any social media similar to what we have here? >> https://ournetworks.ca/about/

Alteratively, you can open a PR the website and/or this repo with all those details!

**Comment by thinkbulecount2** [comment]
Hey @dcwalk I'll do that this weekend if that's cool! (I suck at writing bios hahaha)

**Comment by dcwalk** [comment]
Just a gentle ping @thinkbulecount2 -- I'm happy to help craft a bio if you'd like to chat on this

**Comment by thinkbulecount2** [comment]
@dcwalk That would be awesome!!! Thank you!

**Comment by dcwalk** [comment]
Okay we got an updated pass on bios, closing this as done! Completing tasks! Incrementally! :tada:
