### ISSUE TITLE
Research zines for the Zine Library

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2019#52]
Collecting a list of zines for our Zine Library:

| Name  | Cost  | PDF link  | Print Link  |
|----------|--------|-------------|--------------|
| [n-o-d-e zine](https://n-o-d-e.net/zine/index.html)  | Free PDF, Paid Print  | [🔗 dat](dat://d5f52282d8277c323abcd838e7b1e62113af6dfa70f3c7316ec004911881ec41)  |   |
| [Wizard Zines (Julia Evans)](https://wizardzines.com/)  | Paid PDF  |   |   |
| [People's Open Build Your Own Internet](https://github.com/sudomesh/propaganda/tree/master/handouts)  |  Free |  [🔗](https://github.com/sudomesh/propaganda/blob/master/handouts/byoi_zine.pdf)  |   |
| [CrimethInc Zines](https://crimethinc.com/zines)  | Various  |   |   |
|  |   |   |   |
|  |   |   |   |

Places to look: 
- Internet Archive has tons of relevant zines
- [Toronto Tech Zines](https://totz.ca)
- [Toronto Zine Library](https://www.torontozinelibrary.org/catalogue/opac/)
- [New York Tech Zine Fair](https://techzinefair.org/)
- Allied Media Projects / Detroit Digital Tech
- Tech Workers Coalition (Bug Report!)
- Dat Zine space
- Call for Zines on Scuttleverse?

**Comment by thinkbulecount2** [comment]
[BubbleSort Zines](https://shop.bubblesort.io/)

**Comment by dcwalk** [comment]
Just a brain dump for now:

- DIY Studio (TORONTO!)
- That one about Chemical Valley (TORONTO!)
- The Society for the Diffusion of Useful Knowledge (Toronto!)
- TWC Bug Report
- Pervasive Labour Union zine "Fed Up" 
- Fucktooth thoughts on Tech
- Punk Planet DIY media
- Tech tools for Activism
- Building Consentful Tech
- Peoples Guide to AI
- Tech Wont Build It
- Design Justice (series)
- Interrupt (historical! from Computer People for Peace)
- Radical Mycology (series)
- Detroit Digital Justice Coalition DDJC (series) :tada:
- Streetfight? (I think they have a tech one, or a utopia one)
- Patterns for Decentralised Organizing
- Lessons in Comm. Tech
- Public Lab's Grassroots Mapping Forum (I have some posters we could put up!)
- Community Science Forum
- ONE OF THE BEST: Precarias a la deriva

**Comment by dcwalk** [comment]
More thoughts (also incls. journals/magazines):

- Processed World ([Chris Carlsson](http://www.chriscarlsson.com/archives/))...https://notesfrombelow.org/article/processed-world
- Logic Mag https://logicmag.io/
- Notes from Below: https://notesfrombelow.org/archives
- Upping the Anti (Toronto)
- Briarpatch (Winnipeg? I have a subscription and maybe some backissues)
- Red Pepper (UK I have a subscription and maybe some backissues)
- Solidarity Economy Workbook: https://ccednet-rcdec.ca/sites/ccednet-rcdec.ca/files/copac_g4.pdf
- Geo Issues: http://www.geo.coop/store

More academic-y:
- Fibreculture http://fibreculturejournal.org/
- Amodern http://amodern.net/
What if we go all libcom website article printing. This makes me think of my uncle :grin: 
- https://libcom.org/library/basics-organising-iww
-

**Comment by dcwalk** [comment]
More thoughts (also incls. journals/magazines):

- Processed World ([Chris Carlsson](http://www.chriscarlsson.com/archives/))...https://notesfrombelow.org/article/processed-world
- Logic Mag https://logicmag.io/
- Notes from Below: https://notesfrombelow.org/archives
- Upping the Anti (Toronto)
- Briarpatch (Winnipeg? I have a subscription and maybe some backissues)
- Red Pepper (UK I have a subscription and maybe some backissues)
- Solidarity Economy Workbook: https://ccednet-rcdec.ca/sites/ccednet-rcdec.ca/files/copac_g4.pdf
- Geo Issues: http://www.geo.coop/store

More academic-y:
- Fibreculture http://fibreculturejournal.org/
- Amodern http://amodern.net/

What if we go all libcom website article printing? 
- https://libcom.org/library/basics-organising-iww

**Comment by thinkbulecount2** [comment]
- [Participatory Mapping](http://docs.altermundi.net/P%C3%A1ginaInicial?action=AttachFile&do=get&target=Participatory+mapping+of+the+libre+community+network.pdf)
- [Libre, Community and Decentralized Networks](http://docs.altermundi.net/P%C3%A1ginaInicial?action=AttachFile&do=get&target=Libre,+community+and+decentralized+networks.pdf)

**Comment by thinkbulecount2** [comment]
- [Queer Privacy](https://leanpub.com/queerprivacy)

**Comment by dcwalk** [comment]
We did the research and @thinkbulecount2 has been building the print list, we should close this and track in #73
