### ISSUE TITLE
Printed Post Up Designs

### ISSUE THREAD

**Issue by garrying** [ournetworks/2019#56]
This list was copied over from 2018:
- [x] Final content
- [x] 8.5x11 post ups (Black/White)
- [x] 8.5x5.5 post ups (Black/White)
- [x] 5.5x4.25 post ups (Black/White)
- [x] 11x17 post ups (stretch)
- [ ] A0 posters (stretch)

**Comment by garrying** [comment]
## 8.5x11
<img width="613" alt="letter-bottom-light@2x" src="https://user-images.githubusercontent.com/227587/61192207-c7d28c80-a680-11e9-9ac3-630b60c9706d.png">

## 8.5x5.5
<img width="613" alt="half-letter@2x" src="https://user-images.githubusercontent.com/227587/61192220-e173d400-a680-11e9-8f68-2fe2492e1cf4.png">

## 5.5x4.25
<img width="307" alt="handbill@2x" src="https://user-images.githubusercontent.com/227587/61192229-f51f3a80-a680-11e9-993d-d5f509c81532.png">

**Comment by dcwalk** [comment]
Pretty much all over these!

Thoughts:
- realized we had to do a confirmation with ISOC, you've seen that email perhaps?
- I wonder if we could streamline to "Sliding scale registration and scholarships available" . I think might flow well on one line?

**Comment by dcwalk** [comment]
Side question: how bad does it look if everything is "RE:" i.e., RE:ENCHANTMENT; RE:FUSAL; etc...

**Comment by garrying** [comment]
## 11×17 (tabloid)
![our-networks-post-ups-tabloid@3x](https://user-images.githubusercontent.com/227587/62337678-a86e9880-b4a3-11e9-8beb-94bc501ede66.png)

## 8.5×11 (letter)
![our-networks-post-ups-letter@3x](https://user-images.githubusercontent.com/227587/62337682-ab698900-b4a3-11e9-9911-af642f43c724.png)

## 8.5×5.5 (half-letter)
![our-networks-post-ups-half-letter@3x](https://user-images.githubusercontent.com/227587/62337688-b15f6a00-b4a3-11e9-9c96-46fb103caf77.png)

## 5.5×4.25 (handbill)
![our-networks-post-ups-handbill@3x](https://user-images.githubusercontent.com/227587/62337699-b9b7a500-b4a3-11e9-8c91-346044ac14d0.png)
