### ISSUE TITLE
Create 2019 Stickers and Buttons

### ISSUE THREAD

**Issue by garrying** [ournetworks/2019#68]
## Buttons
- 1 inch
- 1.25 inch

## Stickers
- Square: 2 inch x 2 inch
- Circle: 2 inch
- Rectangle: 2.25 inch x 1 inch
- Rectangle: 2 inch x 1 inch

**Comment by garrying** [comment]
Note The safety orange looks a bit off because it's on CMKY mode. Thinking we should do a test print before doing the final run.

# Draft Buttons
![Buttons-Sheet@3x](https://user-images.githubusercontent.com/227587/61192113-f69c3300-a67f-11e9-9176-c3c6eaa8f63f.png)

# Draft Stickers
![Stickers-Sheet@3x](https://user-images.githubusercontent.com/227587/61192118-01ef5e80-a680-11e9-93eb-c41ce099bf15.png)

**Comment by dcwalk** [comment]
Super into these initial designs!

I'm a little struck with the 1" pins + 2" round stickers and the outline/framework shapes... something about them feels... noisy in a way that doesn't seem to fit with the aesthetic. I wonder if bricks/construction outlines could be more appropriate and carry through the design aesthetic?

**Comment by garrying** [comment]
# Revised Buttons
![Buttons-Sheet@3x](https://user-images.githubusercontent.com/227587/62095074-43ba0080-b24d-11e9-995b-fcf3ba350a75.png)

# Revised Stickers
![Stickers-Sheet@3x](https://user-images.githubusercontent.com/227587/62095078-46b4f100-b24d-11e9-9217-86a9c1946b66.png)

**Comment by dcwalk** [comment]
So into these!

We'll just have to sort how many of the plain black buttons and stickers we
want based on current inventory. :))
