### ISSUE TITLE
Draft visa invitation letter

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#74]
https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/business/bring-business-guests/organize-international-event-canada.html

A letter that event organizers need to give delegates when they apply for a visa to come to Canada.

The letter should include information on the event to establish:
- the delegate’s purpose of travel to Canada, and
- plans once in Canada.
- The letter should also indicate if financial assistance is given to delegates, such as airline tickets and accommodations.

**Comment by dcwalk** [comment]
Other links: 
- https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/business/bring-business-guests.html#visa
- http://www.cic.gc.ca/english/helpcentre/glossary.asp#letter_of_invitation_to_delegates
- https://visaguide.world/tips/invitation-letter-canada-visa/

**Comment by benhylau** [comment]
I can draft this for Canadian Immigration based on what @dcwalk posted and coordinate with applicants who need a visa. I wrote a bunch for [DWeb Camp for US Immigration](https://github.com/dweb-camp-2019/organizing/issues/7#issuecomment-504850054).

**Comment by benhylau** [comment]
It looks like the info we need from an applicant is the following, based on https://visaguide.world/tips/invitation-letter-canada-visa/

>The full name (first name and last name, as on travel document);
Date of birth;
Contact information (telephone number and email);
Exact address;
The relationship that the applicant has with the person inviting them (Our Networks can fill);
The purpose of the visit to Canada (attending Our Networks, unless there are other purposes);
The duration of the visit;
Where the applicant will stay in Canada and how they will pay for their stay (may need an address of an organizer);
The date when the person will arrive in Canada and the date they will leave (not sure how specific this needs to be);

**Comment by dcwalk** [comment]
@benhylau -- I think we need to clarify which interpretation of the rules is correct: visa invitation, or visa letter for "international event delegate", I provided both bits of info above.
