### ISSUE TITLE
Choose theme and develop expository paragraph

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#8]
We'll need to pick a theme and develop language around it.

Brainstorming happening here: https://hackmd.io/NAHVnJD4So6YYv8Jnn0geg?edit#

**Comment by dcwalk** [comment]
Drafting here: https://docs.google.com/document/d/12o3Nkqy3eJGD5xqr-D_uuSy-nfsJ55jmcVTPcjjvT-I/edit#

**Comment by dcwalk** [comment]
This soft launched: https://github.com/ournetworks/ournetworks.ca/pull/92

Let's wait until end next week to start tweeting? We might have some _dates_ and _venue_ news by then :dancer:

**Comment by ana0** [comment]
Had already posted when this went out, sorry!
