### ISSUE TITLE
Develop plan for remote presenting

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#80]
We have interest for 3-5 sessions presented remotely, here is my summation of the options:

- Recorded video
- Recorded video + live Q&A (timezones matter for schedule)
- Doin' it live <-- most risky, do we want to ask for a fallback?

Questions:
- how do we handle for streaming?

Tracking presentations here:
- [x] Amazonification (45 minute talk) Sun PM
  - live call and Q&A
  - local video
- [x] Solar powered website (30 minutes talk) Sun AM
  - live call and Q&A, TZ: PT
  - possible recorded fallback
- [x] Whose future (30 minute talk) Sat AM
  - recorded talk 
  - live Q&A
- [x] Cryptoeconomics (45 minute talk -- asked to keep recorded portion shorter) Sat PM
  - recorded talk 
  - live Q&A
- [x] Biyi's (8 mins lightning)
- [x] Farhad (8 mins lightning)
---
- [x] Confirm timing works
  - need to switch Whose Future to 5pmish or 9amish (Australian TZs)
  - Solar powered borderline (8amish PT)
  - confirm cryptoeconomics (might be 10pmis BST?)
- [x] Select Q&A platform

**Comment by ana0** [comment]
Fyi: I've reached out to a friend in Berlin who has set up ... probably the most effective telepresence I've ever seen to learn about what tools they used/how they did it. Will update

**Comment by benhylau** [comment]
Emails from #119 sent to remote presenters. My next step will be to gather the pre-recorded talks on September 17.

**Comment by dcwalk** [comment]
We did this! Closing :taco:
