### ISSUE TITLE
Curate screenings for Saturday evening

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#83]
Updated with tracking TODOs:
- [x] long list selections
- [x] voting and shortlisting selections
- [x] send out invites
- [x] confirmed screening list:
- add to website -> #92 

---- 

We've decided to commit to an evening of screenings (hopefully in the park! see: #60 :point_left:  ), we need to curate that evening.

**Comment by ana0** [comment]
Making a note so it doesn't get lost: would really like to reach out to Bahar Noorizadeh about this work, but waiting on budget to offer an honorarium http://www.baharnoorizadeh.com/after-scarcity

**Comment by garrying** [comment]
I had a quick think of possible additions:
- https://geocinema.network/
- A Tour of the AC-1 Transatlantic Submarine Cable, Lance Wakeling, https://vimeo.com/65776201
- Internet Machine, Timo Arnall, http://www.elasticspace.com/2014/05/internet-machine
- the ideal, Yuri Pattison, https://vimeo.com/142081282
- https://vimeo.com/309715467
- http://sprawl.space/
- https://vimeo.com/116314844

**Comment by dcwalk** [comment]
Here is the one that we could ask about whether there is a shorter version of (though I think it is 45 mins): [The Quiet Zone](https://vimeo.com/209414776)

**Comment by garrying** [comment]
Wide-ranging list: https://docs.google.com/document/d/1tvlqxuLFXTFen4flzEGz7HlCwyyD64cU785fkmh8yco/edit

**Comment by ana0** [comment]
Note to self: do not forget to find a screen

**Comment by dcwalk** [comment]
Can we make a total A/V list that combines all our needs across areas? this could take the form of a load in doc.

**Comment by dcwalk** [comment]
We did this and should close off in #92
