### ISSUE TITLE
Pick dates

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#9]
We are winnowing down dates based on organizer availability here: https://hackmd.io/NAHVnJD4So6YYv8Jnn0geg?edit#

**Comment by benhylau** [comment]
Other events:
August 21 - 25 [Chaos Communication Camp 2019](https://wiki.das-labor.org/w/Veranstaltung/camp2019)

**Comment by dcwalk** [comment]
Update: In #19 this weekend we checked-in and consensed to host OurNets 2019 in the Fall period, preferencing end September and beginning October!

Goal is to decide next meeting, Feb 2, 2019

**Comment by dcwalk** [comment]
We are closing in:
- Consensed on end-Sept
- Looking at weekend: Sept 27-28 
- Questions on scope of event, number of days before/after to resolve

**Comment by dcwalk** [comment]
We are waiting to hear back on venue, we have two ranges: 

- September 19-23 (have booking request in)
- September 26-29

**Comment by dcwalk** [comment]
We have our better dates: **Sept 20-22** with **Exhibition Sept 20-24** and a more **workshoppy load-in Sept 19-20**

**Comment by dcwalk** [comment]
We have dates!! :tada:
