### ISSUE TITLE
Kickoff Party 

### ISSUE THREAD

**Issue by ana0** [ournetworks/2019#95]
- [x] Include kickoff details on website
- [x] Announce kickoff details on social
- [x] Confirm needed gear with TMAC
- [x] ... stretch goal ... make flyer, post kickoff info on meetups/toronto event sites <-- we did a public flyer!

Minimum viable kickoff equipment:

- [x] PA
- [x] a projector
- [x] power bar
- [x] table
- [x] somewhere to put projector?

Other things to do:
- [x] Handle bar 
- [x] lite catering
- [x] non-alcoholic drinks
  - [x] mate
  - [x] sparkling water

**Comment by ana0** [comment]
Have approached https://paleeyesmusic.bandcamp.com/

**Comment by dcwalk** [comment]
We have all the equipment! I've added notes to our sheet: https://docs.google.com/spreadsheets/d/1g32Cu8Gl-E6eb0UM5JMNuMANKJK-yfSBPDtzjr_l24I/edit#gid=0 

I think we can close

**Comment by dcwalk** [comment]
Note on alcohol: 

# Kickoff 


## Order

beer+cider (24 servings / flat / $3.50 per serving)

- ontario, 2 styles beer, 1 cider, tallcans at $3.25/can 
- vibe: not overly hoppy, low alcohol (nothing over 6%)

- 2 cases x pale ale (e.g., Great Lakes Brewery Canuck Pale Ale, Conductors Craft Ale, Mackinnon 8 Man)
- 2 cases x lager (e.g., Woodhouse, Ace Hill, )
- 1/2 case x dry, unflavoured cide (e.g., Pommies, Spirit Tree, Ardiel)

wine  (6 servings / bottle / $2.50 per serving)

- ontario, 2 styles, red and white at $10-13/bottle
- vibe: fruity, refreshing, no one will be offended

- 3 x red, pinot noir or gamay noir (e.g., Magnotta Pinot Noir, Pelee Island, 13th Street)
- 3 x white, sauvignon blanc or pinot grigio (e.g. Small Talk, Peller, Farm Girl)

1-2 cocktails (16 servings / bottles / $5.00 per serving b/c mixes)

- 1 750 mL bottle Wild Turkey                       $34
- 1 750 mL bottle Bombay Sapphire London Dry Gin    $30

Guess: 

$351 beer and cider (108)
$ 78 wine (36)
$ 65 alcohol (32)
====
$494
  16 deposit
  64 tax
$574 total 

Imagining 80 people
Roughly ~166 servings (2 per person) and ~3.50 cost per serving.
30 drink tickets means $4.25 cost per serving
Sell for $6, cocktails $8?

...$120-200 for Ceit in revenue for 3 hours incl. setup depending on sales.

Recommend:
- potentially cut one alcohol and have only one signature drink 
- return unopened flats / bottles with original receipt to lcbo


- 2 cases x pale ale (e.g., Great Lakes Brewery Canuck Pale Ale, Conductors Craft Ale)
- 2 cases x lager (e.g., Woodhouse, Ace Hill)
- 1/2 case x dry, unflavoured cide (e.g., Spirit Tree, Ardiel)
- 3 x red, pinot noir or gamay noir (e.g., Magnotta Pinot Noir, Pelee Island)
- 3 x white, sauvignon blanc or pinot grigio (e.g. Small Talk, Peller, Farm Girl)
- 1 750 mL bottle Wild Turkey                      
- 1 750 mL bottle Bombay Sapphire London Dry Gin
