### ISSUE TITLE
Video Production Assets

### ISSUE THREAD

**Issue by Shrinks99** [ournetworks/2019#96]
As promised here is the first draft of our video assets for review! @garrying @dcwalk

**The between streams graphic**
![between-presentations](https://user-images.githubusercontent.com/5672810/63233703-b3ddf580-c1ff-11e9-9b74-f5f00d29a74f.png)

**The lower third**
![lower-third-template](https://user-images.githubusercontent.com/5672810/63233752-f273b000-c1ff-11e9-9629-4d500ae87ce8.png)

Content is largely unchanged from last year with the exception of sponsors, I also noticed that [TMAC has a new logo on their website](https://www.tomediaarts.org/) and perhaps we should look into obtaining a vector and updating it?  Also should "venue partners" be singular?  AFAIK there is only one venue this year.

**Comment by dcwalk** [comment]
I'll follow up with TMAC RE: logo, good catch.

Feedback:
- The yellow hatching overhanging on the bottom is a little visually distracting
- The name of the conference isn't present anywhere. I think it should be included in the in-between streams graphic and follow the weighting with respect to the logo as it does on the website
- we don't capitalize our twitter and so for consistency it should be `@_ournetworks`

**Comment by Shrinks99** [comment]
Bummer, the yellow hatching was my favourite part of that graphic. :/  I’ll do a version with it off so we can compare.

While the talk name is definitely the most important thing in the program usually lower thirds put a focus on the person with a secondary line for a credential or in this case the talk name.  This is also what we used last year and I’m inclined to keep it the same?  As with all things if everyone else is super not cool with that it will be fixed.

I like having a hashtag, will change to OurNetworks2019 for now but if we want a different one later that’s obviously an easy fix.

Next submissions will not have reversed type, will also check the contrast.

Everything else seems good to me and I’ll make those changes.  Next round will be submitted as a PR.

**Comment by garrying** [comment]
+1 to @dcwalk's feedback

>This is also what we used last year and I’m inclined to keep it the same?

- I think this is worth revising, along with reducing font sizing delta between the top and lower lines (Disclosure: I'm not super into lower third graphics in general) 
- Inclined to remove the hashtag in the lower third comp
- `Coming up` seems unneeded
-  `Tier 1 ...` etc.: We've been using normal weight on the website
- Maybe there's a opportunity to use the cutout and drop shadow elements?
- We also has an idea of a scrolling marquee in the design concept (could be sick)

**Comment by Shrinks99** [comment]
@garrying and I have created some newer versions – These should hit most of the notes!

One caveat is that the sponsors section is not finalized as in-kind sponsors will have to still be added.  Please disregard the spacing of that area, it will be laid out similar to last year's once that is all ready to be finaled.

![nostream-01](https://user-images.githubusercontent.com/5672810/63559167-109e2080-c51e-11e9-8651-51aba9010709.png)
![lower-third-preview](https://user-images.githubusercontent.com/5672810/63559168-109e2080-c51e-11e9-9955-3e504ee1314c.png)

**Comment by dcwalk** [comment]
Great! Can you move this as a PR to the artwork repo? You can update the files with the final sponsor logos and we can lock in closer to.

**Comment by Shrinks99** [comment]
> Great! Can you move this as a PR to the artwork repo? You can update the files with the final sponsor logos and we can lock in closer to.

Yes!  Done: https://github.com/ournetworks/artwork/pull/18, sorry I didn't just do this initially.

**Comment by benhylau** [comment]
Add Infura & Gamma Space logos. They will be posted here: https://github.com/ournetworks/ournetworks.ca/tree/master/images/logos

**Comment by benhylau** [comment]
@Shrinks99 oops they are on this branch https://github.com/ournetworks/ournetworks.ca/tree/september-update/images/logos waiting to be merged into master, but you can use them now

**Comment by Shrinks99** [comment]
Something to note, I don't believe we should be using the Infura version with the logomark, as per their [brand guidelines](https://infura.io/presskit):

> This centrally aligned lockup should only be used when it can be centered within a page or layout.

They provide an alternate version with just the wordmark which we should probably switch to.

**Comment by benhylau** [comment]
Thanks for pointing that out @Shrinks99 
@dcwalk shall we change both website and media to a different infura logo?

**Comment by garrying** [comment]
Updated website logo will be updated with https://github.com/ournetworks/ournetworks.ca/pull/133

**Comment by dcwalk** [comment]
These were merged in, I'm closing
