### ISSUE TITLE
Screenprinting (onsite and pre-order)

### ISSUE THREAD

**Issue by ana0** [ournetworks/2019#98]
Onsite:

- [x] finalize art
- [x] screen
- [x] clamps
- [x] squeegee(s)
- [x] board/table for clamps
- [x] confirm water situation at TMAC
- [x] buy ink (black and white)
- [x] source a selection of second hand t shirts in a variety of sizes
- [x] Sarah will find her blank tote stash, and donate it
- [x] notify attendees about bring-your-own-shirt
- [x] put screenprinting timeslots on the program
- [x] decide on recommended donation
- [x] dropsheet
- [x] wash tubs

Pre-order:

- [x] confirm with sugarbomb (need sizes)
- [x] pay for shirts
- [x] pick up shirts

**Comment by dcwalk** [comment]
This was done at the recent [OPIRG Anti-gallery](https://www.facebook.com/events/631309594018185/) by OCAP folks and the screen seemed fined being set up for a the run of the event -- a couple hours.

**Comment by ana0** [comment]
Question of how many shirts to source leading up to the event remains

**Comment by ana0** [comment]
I probably have some I can donate too

**Comment by dcwalk** [comment]
To help with costing out onsite purchases (which, if I am reading correctly will be):
- ink
- maybe photo emulsion stuff
- tshirts (my pricing from scanning at value village is <$10/shirt)

I've pulled together a swag breakdown for costs, I think we can fit all the above in our budget but need to be mindful: https://docs.google.com/spreadsheets/d/1vNI_1LzYn8_36MxNLmlIxAJSqyLfilyhDQ7qI4I9l70/edit#gid=610609088

**Comment by ana0** [comment]
I think we'll need to purchase ink, but not photo emulsion. And for shirts ... you can get a new shirt for <$5 in Chinatown, which of course doesn't fit our goal of upcycling waste here, but I think we should keep that in mind when thrifting too, and not pay more for used than for new.

**Comment by dcwalk** [comment]
We did this! We went with: $5 suggested donation for own swag, $10 for one of our shirts
