### ISSUE TITLE
Conference social media

### ISSUE THREAD

**Issue by ana0** [ournetworks/2019#99]
Write all the needed tweets leading up to the event, and schedule them in tweetdeck

- [x] write tweets (program, registration reminders, sponsors, zine fair)
- [x] schedule tweets

Spreadsheet here: https://docs.google.com/spreadsheets/d/1MLSbf4me0OEIT-zg4tF0D3D2MhQrfb89EEJmYP-QkRw/edit#gid=0

**Comment by dcwalk** [comment]
Let's close this out as done! All the tweets were scheduled :tada:
